name: Coverage
on:
  repository_dispatch:
    # types: [notify]

jobs:
  send_email:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish message
      run: |
        curl -X POST \
         -H "Content-Type: application/json" \  
         -d '{"text": "notify"}' \
         {{secrets.CHAT_HOOK}}
